// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.36.2
// source: internal/pkg/tunnel/tunnel.proto

package tunnel

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Step int32

const (
	Step_REQUEST       Step = 0
	Step_RESPONSE      Step = 1
	Step_POST_RESPONSE Step = 2
)

// Enum value maps for Step.
var (
	Step_name = map[int32]string{
		0: "REQUEST",
		1: "RESPONSE",
		2: "POST_RESPONSE",
	}
	Step_value = map[string]int32{
		"REQUEST":       0,
		"RESPONSE":      1,
		"POST_RESPONSE": 2,
	}
)

func (x Step) Enum() *Step {
	p := new(Step)
	*p = x
	return p
}

func (x Step) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Step) Descriptor() protoreflect.EnumDescriptor {
	return file_internal_pkg_tunnel_tunnel_proto_enumTypes[0].Descriptor()
}

func (Step) Type() protoreflect.EnumType {
	return &file_internal_pkg_tunnel_tunnel_proto_enumTypes[0]
}

func (x Step) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Step.Descriptor instead.
func (Step) EnumDescriptor() ([]byte, []int) {
	return file_internal_pkg_tunnel_tunnel_proto_rawDescGZIP(), []int{0}
}

type Status int32

const (
	Status_CONNECTING   Status = 0
	Status_CONNECTED    Status = 1
	Status_RECONNECTING Status = 2
	Status_DISCONNECTED Status = 3
)

// Enum value maps for Status.
var (
	Status_name = map[int32]string{
		0: "CONNECTING",
		1: "CONNECTED",
		2: "RECONNECTING",
		3: "DISCONNECTED",
	}
	Status_value = map[string]int32{
		"CONNECTING":   0,
		"CONNECTED":    1,
		"RECONNECTING": 2,
		"DISCONNECTED": 3,
	}
)

func (x Status) Enum() *Status {
	p := new(Status)
	*p = x
	return p
}

func (x Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Status) Descriptor() protoreflect.EnumDescriptor {
	return file_internal_pkg_tunnel_tunnel_proto_enumTypes[1].Descriptor()
}

func (Status) Type() protoreflect.EnumType {
	return &file_internal_pkg_tunnel_tunnel_proto_enumTypes[1]
}

func (x Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Status.Descriptor instead.
func (Status) EnumDescriptor() ([]byte, []int) {
	return file_internal_pkg_tunnel_tunnel_proto_rawDescGZIP(), []int{1}
}

type ServerMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Record        *Record                `protobuf:"bytes,1,opt,name=record,proto3" json:"record,omitempty"`
	Session       *Session               `protobuf:"bytes,2,opt,name=session,proto3" json:"session,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerMessage) Reset() {
	*x = ServerMessage{}
	mi := &file_internal_pkg_tunnel_tunnel_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerMessage) ProtoMessage() {}

func (x *ServerMessage) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pkg_tunnel_tunnel_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerMessage.ProtoReflect.Descriptor instead.
func (*ServerMessage) Descriptor() ([]byte, []int) {
	return file_internal_pkg_tunnel_tunnel_proto_rawDescGZIP(), []int{0}
}

func (x *ServerMessage) GetRecord() *Record {
	if x != nil {
		return x.Record
	}
	return nil
}

func (x *ServerMessage) GetSession() *Session {
	if x != nil {
		return x.Session
	}
	return nil
}

type ClientMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Record        *Record                `protobuf:"bytes,1,opt,name=record,proto3" json:"record,omitempty"`
	Handshake     *Handshake             `protobuf:"bytes,2,opt,name=handshake,proto3" json:"handshake,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClientMessage) Reset() {
	*x = ClientMessage{}
	mi := &file_internal_pkg_tunnel_tunnel_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientMessage) ProtoMessage() {}

func (x *ClientMessage) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pkg_tunnel_tunnel_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientMessage.ProtoReflect.Descriptor instead.
func (*ClientMessage) Descriptor() ([]byte, []int) {
	return file_internal_pkg_tunnel_tunnel_proto_rawDescGZIP(), []int{1}
}

func (x *ClientMessage) GetRecord() *Record {
	if x != nil {
		return x.Record
	}
	return nil
}

func (x *ClientMessage) GetHandshake() *Handshake {
	if x != nil {
		return x.Handshake
	}
	return nil
}

type Handshake struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClientId      string                 `protobuf:"bytes,1,opt,name=clientId,proto3" json:"clientId,omitempty"`
	ClientKey     []byte                 `protobuf:"bytes,2,opt,name=clientKey,proto3" json:"clientKey,omitempty"`
	AllowReaders  bool                   `protobuf:"varint,3,opt,name=allowReaders,proto3" json:"allowReaders,omitempty"`
	Bearer        []byte                 `protobuf:"bytes,4,opt,name=bearer,proto3" json:"bearer,omitempty"`
	SharedKey     []byte                 `protobuf:"bytes,5,opt,name=sharedKey,proto3" json:"sharedKey,omitempty"`
	ExpireAt      int64                  `protobuf:"varint,6,opt,name=expireAt,proto3" json:"expireAt,omitempty"`
	Version       string                 `protobuf:"bytes,7,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Handshake) Reset() {
	*x = Handshake{}
	mi := &file_internal_pkg_tunnel_tunnel_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Handshake) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Handshake) ProtoMessage() {}

func (x *Handshake) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pkg_tunnel_tunnel_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Handshake.ProtoReflect.Descriptor instead.
func (*Handshake) Descriptor() ([]byte, []int) {
	return file_internal_pkg_tunnel_tunnel_proto_rawDescGZIP(), []int{2}
}

func (x *Handshake) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *Handshake) GetClientKey() []byte {
	if x != nil {
		return x.ClientKey
	}
	return nil
}

func (x *Handshake) GetAllowReaders() bool {
	if x != nil {
		return x.AllowReaders
	}
	return false
}

func (x *Handshake) GetBearer() []byte {
	if x != nil {
		return x.Bearer
	}
	return nil
}

func (x *Handshake) GetSharedKey() []byte {
	if x != nil {
		return x.SharedKey
	}
	return nil
}

func (x *Handshake) GetExpireAt() int64 {
	if x != nil {
		return x.ExpireAt
	}
	return 0
}

func (x *Handshake) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

type Session struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ClientId        string                 `protobuf:"bytes,1,opt,name=clientId,proto3" json:"clientId,omitempty"`
	Hostname        string                 `protobuf:"bytes,2,opt,name=hostname,proto3" json:"hostname,omitempty"`
	HttpPort        string                 `protobuf:"bytes,3,opt,name=httpPort,proto3" json:"httpPort,omitempty"`
	HttpsPort       string                 `protobuf:"bytes,4,opt,name=httpsPort,proto3" json:"httpsPort,omitempty"`
	Bearer          []byte                 `protobuf:"bytes,5,opt,name=bearer,proto3" json:"bearer,omitempty"`
	MaxRequestSize  int32                  `protobuf:"varint,6,opt,name=maxRequestSize,proto3" json:"maxRequestSize,omitempty"`
	MaxResponseSize int32                  `protobuf:"varint,7,opt,name=maxResponseSize,proto3" json:"maxResponseSize,omitempty"`
	ResponseTimeout int64                  `protobuf:"varint,8,opt,name=responseTimeout,proto3" json:"responseTimeout,omitempty"`
	ExpireAt        int64                  `protobuf:"varint,9,opt,name=expireAt,proto3" json:"expireAt,omitempty"`
	Status          Status                 `protobuf:"varint,10,opt,name=status,proto3,enum=tunnel.Status" json:"status,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Session) Reset() {
	*x = Session{}
	mi := &file_internal_pkg_tunnel_tunnel_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Session) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Session) ProtoMessage() {}

func (x *Session) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pkg_tunnel_tunnel_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Session.ProtoReflect.Descriptor instead.
func (*Session) Descriptor() ([]byte, []int) {
	return file_internal_pkg_tunnel_tunnel_proto_rawDescGZIP(), []int{3}
}

func (x *Session) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *Session) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *Session) GetHttpPort() string {
	if x != nil {
		return x.HttpPort
	}
	return ""
}

func (x *Session) GetHttpsPort() string {
	if x != nil {
		return x.HttpsPort
	}
	return ""
}

func (x *Session) GetBearer() []byte {
	if x != nil {
		return x.Bearer
	}
	return nil
}

func (x *Session) GetMaxRequestSize() int32 {
	if x != nil {
		return x.MaxRequestSize
	}
	return 0
}

func (x *Session) GetMaxResponseSize() int32 {
	if x != nil {
		return x.MaxResponseSize
	}
	return 0
}

func (x *Session) GetResponseTimeout() int64 {
	if x != nil {
		return x.ResponseTimeout
	}
	return 0
}

func (x *Session) GetExpireAt() int64 {
	if x != nil {
		return x.ExpireAt
	}
	return 0
}

func (x *Session) GetStatus() Status {
	if x != nil {
		return x.Status
	}
	return Status_CONNECTING
}

type Request struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Proto         string                 `protobuf:"bytes,1,opt,name=proto,proto3" json:"proto,omitempty"`
	Method        string                 `protobuf:"bytes,2,opt,name=method,proto3" json:"method,omitempty"`
	Url           string                 `protobuf:"bytes,3,opt,name=url,proto3" json:"url,omitempty"`
	Path          string                 `protobuf:"bytes,4,opt,name=path,proto3" json:"path,omitempty"`
	Header        map[string]string      `protobuf:"bytes,5,rep,name=header,proto3" json:"header,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Body          []byte                 `protobuf:"bytes,6,opt,name=body,proto3" json:"body,omitempty"`
	RemoteAddr    string                 `protobuf:"bytes,7,opt,name=remoteAddr,proto3" json:"remoteAddr,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Request) Reset() {
	*x = Request{}
	mi := &file_internal_pkg_tunnel_tunnel_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Request) ProtoMessage() {}

func (x *Request) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pkg_tunnel_tunnel_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Request.ProtoReflect.Descriptor instead.
func (*Request) Descriptor() ([]byte, []int) {
	return file_internal_pkg_tunnel_tunnel_proto_rawDescGZIP(), []int{4}
}

func (x *Request) GetProto() string {
	if x != nil {
		return x.Proto
	}
	return ""
}

func (x *Request) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *Request) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *Request) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *Request) GetHeader() map[string]string {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *Request) GetBody() []byte {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *Request) GetRemoteAddr() string {
	if x != nil {
		return x.RemoteAddr
	}
	return ""
}

type Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Proto         string                 `protobuf:"bytes,1,opt,name=proto,proto3" json:"proto,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	Code          int32                  `protobuf:"varint,3,opt,name=code,proto3" json:"code,omitempty"`
	Header        map[string]string      `protobuf:"bytes,4,rep,name=header,proto3" json:"header,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Body          []byte                 `protobuf:"bytes,5,opt,name=body,proto3" json:"body,omitempty"`
	Elapsed       int64                  `protobuf:"varint,6,opt,name=elapsed,proto3" json:"elapsed,omitempty"`
	ServerElapsed int64                  `protobuf:"varint,7,opt,name=serverElapsed,proto3" json:"serverElapsed,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Response) Reset() {
	*x = Response{}
	mi := &file_internal_pkg_tunnel_tunnel_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Response) ProtoMessage() {}

func (x *Response) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pkg_tunnel_tunnel_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Response.ProtoReflect.Descriptor instead.
func (*Response) Descriptor() ([]byte, []int) {
	return file_internal_pkg_tunnel_tunnel_proto_rawDescGZIP(), []int{5}
}

func (x *Response) GetProto() string {
	if x != nil {
		return x.Proto
	}
	return ""
}

func (x *Response) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Response) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *Response) GetHeader() map[string]string {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *Response) GetBody() []byte {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *Response) GetElapsed() int64 {
	if x != nil {
		return x.Elapsed
	}
	return 0
}

func (x *Response) GetServerElapsed() int64 {
	if x != nil {
		return x.ServerElapsed
	}
	return 0
}

type Record struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Request       *Request               `protobuf:"bytes,2,opt,name=request,proto3" json:"request,omitempty"`
	Response      *Response              `protobuf:"bytes,3,opt,name=response,proto3" json:"response,omitempty"`
	Step          Step                   `protobuf:"varint,4,opt,name=step,proto3,enum=tunnel.Step" json:"step,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Record) Reset() {
	*x = Record{}
	mi := &file_internal_pkg_tunnel_tunnel_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Record) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Record) ProtoMessage() {}

func (x *Record) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pkg_tunnel_tunnel_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Record.ProtoReflect.Descriptor instead.
func (*Record) Descriptor() ([]byte, []int) {
	return file_internal_pkg_tunnel_tunnel_proto_rawDescGZIP(), []int{6}
}

func (x *Record) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Record) GetRequest() *Request {
	if x != nil {
		return x.Request
	}
	return nil
}

func (x *Record) GetResponse() *Response {
	if x != nil {
		return x.Response
	}
	return nil
}

func (x *Record) GetStep() Step {
	if x != nil {
		return x.Step
	}
	return Step_REQUEST
}

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_internal_pkg_tunnel_tunnel_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pkg_tunnel_tunnel_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_internal_pkg_tunnel_tunnel_proto_rawDescGZIP(), []int{7}
}

var File_internal_pkg_tunnel_tunnel_proto protoreflect.FileDescriptor

const file_internal_pkg_tunnel_tunnel_proto_rawDesc = "" +
	"\n" +
	" internal/pkg/tunnel/tunnel.proto\x12\x06tunnel\"b\n" +
	"\rServerMessage\x12&\n" +
	"\x06record\x18\x01 \x01(\v2\x0e.tunnel.RecordR\x06record\x12)\n" +
	"\asession\x18\x02 \x01(\v2\x0f.tunnel.SessionR\asession\"h\n" +
	"\rClientMessage\x12&\n" +
	"\x06record\x18\x01 \x01(\v2\x0e.tunnel.RecordR\x06record\x12/\n" +
	"\thandshake\x18\x02 \x01(\v2\x11.tunnel.HandshakeR\thandshake\"\xd5\x01\n" +
	"\tHandshake\x12\x1a\n" +
	"\bclientId\x18\x01 \x01(\tR\bclientId\x12\x1c\n" +
	"\tclientKey\x18\x02 \x01(\fR\tclientKey\x12\"\n" +
	"\fallowReaders\x18\x03 \x01(\bR\fallowReaders\x12\x16\n" +
	"\x06bearer\x18\x04 \x01(\fR\x06bearer\x12\x1c\n" +
	"\tsharedKey\x18\x05 \x01(\fR\tsharedKey\x12\x1a\n" +
	"\bexpireAt\x18\x06 \x01(\x03R\bexpireAt\x12\x18\n" +
	"\aversion\x18\a \x01(\tR\aversion\"\xd3\x02\n" +
	"\aSession\x12\x1a\n" +
	"\bclientId\x18\x01 \x01(\tR\bclientId\x12\x1a\n" +
	"\bhostname\x18\x02 \x01(\tR\bhostname\x12\x1a\n" +
	"\bhttpPort\x18\x03 \x01(\tR\bhttpPort\x12\x1c\n" +
	"\thttpsPort\x18\x04 \x01(\tR\thttpsPort\x12\x16\n" +
	"\x06bearer\x18\x05 \x01(\fR\x06bearer\x12&\n" +
	"\x0emaxRequestSize\x18\x06 \x01(\x05R\x0emaxRequestSize\x12(\n" +
	"\x0fmaxResponseSize\x18\a \x01(\x05R\x0fmaxResponseSize\x12(\n" +
	"\x0fresponseTimeout\x18\b \x01(\x03R\x0fresponseTimeout\x12\x1a\n" +
	"\bexpireAt\x18\t \x01(\x03R\bexpireAt\x12&\n" +
	"\x06status\x18\n" +
	" \x01(\x0e2\x0e.tunnel.StatusR\x06status\"\x81\x02\n" +
	"\aRequest\x12\x14\n" +
	"\x05proto\x18\x01 \x01(\tR\x05proto\x12\x16\n" +
	"\x06method\x18\x02 \x01(\tR\x06method\x12\x10\n" +
	"\x03url\x18\x03 \x01(\tR\x03url\x12\x12\n" +
	"\x04path\x18\x04 \x01(\tR\x04path\x123\n" +
	"\x06header\x18\x05 \x03(\v2\x1b.tunnel.Request.HeaderEntryR\x06header\x12\x12\n" +
	"\x04body\x18\x06 \x01(\fR\x04body\x12\x1e\n" +
	"\n" +
	"remoteAddr\x18\a \x01(\tR\n" +
	"remoteAddr\x1a9\n" +
	"\vHeaderEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x91\x02\n" +
	"\bResponse\x12\x14\n" +
	"\x05proto\x18\x01 \x01(\tR\x05proto\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x12\n" +
	"\x04code\x18\x03 \x01(\x05R\x04code\x124\n" +
	"\x06header\x18\x04 \x03(\v2\x1c.tunnel.Response.HeaderEntryR\x06header\x12\x12\n" +
	"\x04body\x18\x05 \x01(\fR\x04body\x12\x18\n" +
	"\aelapsed\x18\x06 \x01(\x03R\aelapsed\x12$\n" +
	"\rserverElapsed\x18\a \x01(\x03R\rserverElapsed\x1a9\n" +
	"\vHeaderEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x93\x01\n" +
	"\x06Record\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12)\n" +
	"\arequest\x18\x02 \x01(\v2\x0f.tunnel.RequestR\arequest\x12,\n" +
	"\bresponse\x18\x03 \x01(\v2\x10.tunnel.ResponseR\bresponse\x12 \n" +
	"\x04step\x18\x04 \x01(\x0e2\f.tunnel.StepR\x04step\"\a\n" +
	"\x05Empty*4\n" +
	"\x04Step\x12\v\n" +
	"\aREQUEST\x10\x00\x12\f\n" +
	"\bRESPONSE\x10\x01\x12\x11\n" +
	"\rPOST_RESPONSE\x10\x02*K\n" +
	"\x06Status\x12\x0e\n" +
	"\n" +
	"CONNECTING\x10\x00\x12\r\n" +
	"\tCONNECTED\x10\x01\x12\x10\n" +
	"\fRECONNECTING\x10\x02\x12\x10\n" +
	"\fDISCONNECTED\x10\x032r\n" +
	"\x06Tunnel\x12<\n" +
	"\x06Tunnel\x12\x15.tunnel.ClientMessage\x1a\x15.tunnel.ServerMessage\"\x00(\x010\x01\x12*\n" +
	"\bTestConn\x12\r.tunnel.Empty\x1a\r.tunnel.Empty\"\x00B\x15Z\x13internal/pkg/tunnelb\x06proto3"

var (
	file_internal_pkg_tunnel_tunnel_proto_rawDescOnce sync.Once
	file_internal_pkg_tunnel_tunnel_proto_rawDescData []byte
)

func file_internal_pkg_tunnel_tunnel_proto_rawDescGZIP() []byte {
	file_internal_pkg_tunnel_tunnel_proto_rawDescOnce.Do(func() {
		file_internal_pkg_tunnel_tunnel_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_pkg_tunnel_tunnel_proto_rawDesc), len(file_internal_pkg_tunnel_tunnel_proto_rawDesc)))
	})
	return file_internal_pkg_tunnel_tunnel_proto_rawDescData
}

var file_internal_pkg_tunnel_tunnel_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_internal_pkg_tunnel_tunnel_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_internal_pkg_tunnel_tunnel_proto_goTypes = []any{
	(Step)(0),             // 0: tunnel.Step
	(Status)(0),           // 1: tunnel.Status
	(*ServerMessage)(nil), // 2: tunnel.ServerMessage
	(*ClientMessage)(nil), // 3: tunnel.ClientMessage
	(*Handshake)(nil),     // 4: tunnel.Handshake
	(*Session)(nil),       // 5: tunnel.Session
	(*Request)(nil),       // 6: tunnel.Request
	(*Response)(nil),      // 7: tunnel.Response
	(*Record)(nil),        // 8: tunnel.Record
	(*Empty)(nil),         // 9: tunnel.Empty
	nil,                   // 10: tunnel.Request.HeaderEntry
	nil,                   // 11: tunnel.Response.HeaderEntry
}
var file_internal_pkg_tunnel_tunnel_proto_depIdxs = []int32{
	8,  // 0: tunnel.ServerMessage.record:type_name -> tunnel.Record
	5,  // 1: tunnel.ServerMessage.session:type_name -> tunnel.Session
	8,  // 2: tunnel.ClientMessage.record:type_name -> tunnel.Record
	4,  // 3: tunnel.ClientMessage.handshake:type_name -> tunnel.Handshake
	1,  // 4: tunnel.Session.status:type_name -> tunnel.Status
	10, // 5: tunnel.Request.header:type_name -> tunnel.Request.HeaderEntry
	11, // 6: tunnel.Response.header:type_name -> tunnel.Response.HeaderEntry
	6,  // 7: tunnel.Record.request:type_name -> tunnel.Request
	7,  // 8: tunnel.Record.response:type_name -> tunnel.Response
	0,  // 9: tunnel.Record.step:type_name -> tunnel.Step
	3,  // 10: tunnel.Tunnel.Tunnel:input_type -> tunnel.ClientMessage
	9,  // 11: tunnel.Tunnel.TestConn:input_type -> tunnel.Empty
	2,  // 12: tunnel.Tunnel.Tunnel:output_type -> tunnel.ServerMessage
	9,  // 13: tunnel.Tunnel.TestConn:output_type -> tunnel.Empty
	12, // [12:14] is the sub-list for method output_type
	10, // [10:12] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_internal_pkg_tunnel_tunnel_proto_init() }
func file_internal_pkg_tunnel_tunnel_proto_init() {
	if File_internal_pkg_tunnel_tunnel_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_pkg_tunnel_tunnel_proto_rawDesc), len(file_internal_pkg_tunnel_tunnel_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_pkg_tunnel_tunnel_proto_goTypes,
		DependencyIndexes: file_internal_pkg_tunnel_tunnel_proto_depIdxs,
		EnumInfos:         file_internal_pkg_tunnel_tunnel_proto_enumTypes,
		MessageInfos:      file_internal_pkg_tunnel_tunnel_proto_msgTypes,
	}.Build()
	File_internal_pkg_tunnel_tunnel_proto = out.File
	file_internal_pkg_tunnel_tunnel_proto_goTypes = nil
	file_internal_pkg_tunnel_tunnel_proto_depIdxs = nil
}
